[FTL-1678] Move TestmailInbox into a separate package
affinityproject/affinidi-core-sdk pull request #174
Opened 2021-10-29 14:56 UTC by ezgi-affinidi

https://lemmatree.atlassian.net/browse/FTL-1678

2021-11-01 09:37 UTC, inga-affinidi requested changes

2021-11-01 09:37 UTC, inga-affinidi commented on sdk/core/package.json
> +    "@affinidi/test-helpers": "^1.0.0",
Please maintain the alphabetic order here

2021-11-01 09:37 UTC, inga-affinidi commented on sdk/test-helpers/CHANGELOG.md
> +# release 6.0.0-beta.20 (2021-10-20)
This is probably here by mistake?

2021-11-01 09:37 UTC, inga-affinidi commented on sdk/test-helpers/README.md
> +> Please note that versions `>=4.2.6 <=5.0.0` might not work properly (see [this PR](https://github.com/affinityproject/affinidi-core-sdk/pull/105)).
This is probably here by mistake?

2021-11-01 09:37 UTC, inga-affinidi commented on sdk/test-helpers/package.json
> +    "@types/ethereumjs-util": "5.2.0",
Please remove unused dependencies

2021-11-01 09:37 UTC, inga-affinidi commented on sdk/test-helpers/package.json
> +    "test:integration": "",
You could have the commands there (like in core-sdk etc), just not have any actual tests, to make adding them in the future easier.

2021-11-15 13:02 UTC, vitalyrudenko-affinidi commented
Should we add one or two integration tests here?

2021-12-21 05:41 UTC, vitalyrudenko-affinidi commented
Closing for the time being

2021-12-21 05:41 UTC, closed without merging