[NEP-779] Add VC_Saved event
affinityproject/affinidi-core-sdk pull request #3
Opened 2020-10-05 08:41 UTC by everdark

https://replika.atlassian.net/browse/NEP-779

Related to:

+ https://github.com/affinityproject/affinity-metrics-lib/pull/11
+ https://github.com/affinityproject/affinity-metrics/pull/77

2020-10-06 03:45 UTC, rbrazhnyk requested changes
Please see minor comments

2020-10-06 03:45 UTC, rbrazhnyk commented on sdk/browser/src/AffinityWallet.ts
>      return this.saveEncryptedCredentials(encryptedCredentials)
we can have something like:

```ts
  const result = await this.saveEncryptedCredentials(encryptedCredentials)

  this._sendVCSavedMetrics(data)
  // NOTE: what if creds actually were not saved in the vault? Follow up with Isaak/Dustin on this - should we parse the response to define if we need to send the metrics

  return result
```

2020-10-06 03:45 UTC, rbrazhnyk commented on sdk/core/src/CommonNetworkMember.ts
> +import { EventCategory, EventName, VcMetadata } from '@affinityproject/affinity-metrics-lib'
as agreed, let's have `Metadata` in metrics-lib

2020-10-06 03:45 UTC, rbrazhnyk commented on sdk/core/src/CommonNetworkMember.ts
> +      if (typeof issuer === 'string') {
please check if there would not be any linter issues. `npm run lint`

2020-10-07 12:40 UTC, rbrazhnyk approved these changes
@everdark, adding approval. Please make sure event is saved before merging. Ping me if you need any help here.

2020-10-12 03:39 UTC, rbrazhnyk submitted a review, later dismissed
Please merge metrics-lib, update metrics backend, and after all checks in the pipeline passed there feel free to merge.

2020-10-13 11:17 UTC, ipatka approved these changes

2020-10-13 11:17 UTC, merged